// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace UblSharp
{
    using UnqualifiedDataTypes;
    using CommonAggregateComponents;
    using CommonExtensionComponents;
    
    
    /// <summary>
    /// A document issued by a procurement organization to notify an economic operator whether it has been admitted to or excluded from the tendering process.
    /// <para />ComponentType: ABIE
    /// <para />DictionaryEntryName: Tenderer Qualification Response. Details
    /// <para />ObjectClass: Tenderer Qualification Response
    /// </summary>
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TendererQualificationResponse", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:TendererQualificationResponse-2")]
    [System.Xml.Serialization.XmlRootAttribute("TendererQualificationResponse", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:TendererQualificationResponse-2", IsNullable=false)]
    public partial class TendererQualificationResponseType : BaseDocument
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("CopyIndicator", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IndicatorType @__CopyIndicator;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ContractFolderID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IdentifierType @__ContractFolderID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ContractName", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public System.Collections.Generic.List<TextType> @__ContractName;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("IssueDate", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public DateType @__IssueDate;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("IssueTime", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public TimeType @__IssueTime;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Note", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public System.Collections.Generic.List<TextType> @__Note;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("SenderParty", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType @__SenderParty;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ReceiverParty", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType @__ReceiverParty;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ResolutionDocumentReference", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public DocumentReferenceType @__ResolutionDocumentReference;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("QualificationResolution", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public System.Collections.Generic.List<QualificationResolutionType> @__QualificationResolution;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("AppealTerms", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public AppealTermsType @__AppealTerms;
        
        /// <summary>
        /// Indicates whether this document is a copy (true) or not (false).
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Tenderer Qualification Response. Copy_ Indicator. Indicator
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Tenderer Qualification Response
        /// <para />PropertyTermQualifier: Copy
        /// <para />PropertyTerm: Indicator
        /// <para />RepresentationTerm: Indicator
        /// <para />DataType: Indicator. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public IndicatorType CopyIndicator
        {
            get
            {
                if (__CopyIndicator == null) { __CopyIndicator = new IndicatorType(); }
                return __CopyIndicator;
            }
            set
            {
                __CopyIndicator = value;
            }
        }

        /// <summary>
        /// An identifier, assigned by the sender, for the process file (i.e., record) to which this document belongs.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Tenderer Qualification Response. Contract Folder Identifier. Identifier
        /// <para />Cardinality: 1
        /// <para />ObjectClass: Tenderer Qualification Response
        /// <para />PropertyTerm: Contract Folder Identifier
        /// <para />RepresentationTerm: Identifier
        /// <para />DataType: Identifier. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public IdentifierType ContractFolderID
        {
            get
            {
                if (__ContractFolderID == null) { __ContractFolderID = new IdentifierType(); }
                return __ContractFolderID;
            }
            set
            {
                __ContractFolderID = value;
            }
        }

        /// <summary>
        /// Short title of a contract associated with this Tender.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Tenderer Qualification Response. Contract Name. Text
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Tenderer Qualification Response
        /// <para />PropertyTerm: Contract Name
        /// <para />RepresentationTerm: Text
        /// <para />DataType: Text. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<TextType> ContractName
        {
            get
            {
                if (__ContractName == null) { __ContractName = new System.Collections.Generic.List<TextType>(); }
                return __ContractName;
            }
            set
            {
                __ContractName = value;
            }
        }

        /// <summary>
        /// The date, assigned by the sender, on which this document was issued.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Tenderer Qualification Response. Issue Date. Date
        /// <para />Cardinality: 1
        /// <para />ObjectClass: Tenderer Qualification Response
        /// <para />PropertyTerm: Issue Date
        /// <para />RepresentationTerm: Date
        /// <para />DataType: Date. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public DateType IssueDate
        {
            get
            {
                if (__IssueDate == null) { __IssueDate = new DateType(); }
                return __IssueDate;
            }
            set
            {
                __IssueDate = value;
            }
        }

        /// <summary>
        /// The time, assigned by the sender, at which this document was issued.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Tenderer Qualification Response. Issue Time. Time
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Tenderer Qualification Response
        /// <para />PropertyTerm: Issue Time
        /// <para />RepresentationTerm: Time
        /// <para />DataType: Time. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public TimeType IssueTime
        {
            get
            {
                if (__IssueTime == null) { __IssueTime = new TimeType(); }
                return __IssueTime;
            }
            set
            {
                __IssueTime = value;
            }
        }

        /// <summary>
        /// Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Tenderer Qualification Response. Note. Text
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Tenderer Qualification Response
        /// <para />PropertyTerm: Note
        /// <para />RepresentationTerm: Text
        /// <para />DataType: Text. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<TextType> Note
        {
            get
            {
                if (__Note == null) { __Note = new System.Collections.Generic.List<TextType>(); }
                return __Note;
            }
            set
            {
                __Note = value;
            }
        }

        /// <summary>
        /// The party sending this message.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Tenderer Qualification Response. Sender_ Party. Party
        /// <para />Cardinality: 1
        /// <para />ObjectClass: Tenderer Qualification Response
        /// <para />PropertyTermQualifier: Sender
        /// <para />PropertyTerm: Party
        /// <para />AssociatedObjectClass: Party
        /// <para />RepresentationTerm: Party
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public PartyType SenderParty
        {
            get
            {
                if (__SenderParty == null) { __SenderParty = new PartyType(); }
                return __SenderParty;
            }
            set
            {
                __SenderParty = value;
            }
        }

        /// <summary>
        /// The party receiving this message.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Tenderer Qualification Response. Receiver_ Party. Party
        /// <para />Cardinality: 1
        /// <para />ObjectClass: Tenderer Qualification Response
        /// <para />PropertyTermQualifier: Receiver
        /// <para />PropertyTerm: Party
        /// <para />AssociatedObjectClass: Party
        /// <para />RepresentationTerm: Party
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public PartyType ReceiverParty
        {
            get
            {
                if (__ReceiverParty == null) { __ReceiverParty = new PartyType(); }
                return __ReceiverParty;
            }
            set
            {
                __ReceiverParty = value;
            }
        }

        /// <summary>
        /// A document (e.g., meeting minutes) relating to consideration of tenderer qualifications.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Tenderer Qualification Response. Resolution_ Document Reference. Document Reference
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Tenderer Qualification Response
        /// <para />PropertyTermQualifier: Resolution
        /// <para />PropertyTerm: Document Reference
        /// <para />AssociatedObjectClass: Document Reference
        /// <para />RepresentationTerm: Document Reference
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public DocumentReferenceType ResolutionDocumentReference
        {
            get
            {
                if (__ResolutionDocumentReference == null) { __ResolutionDocumentReference = new DocumentReferenceType(); }
                return __ResolutionDocumentReference;
            }
            set
            {
                __ResolutionDocumentReference = value;
            }
        }

        /// <summary>
        /// An association to the resolution that is being notified
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Tenderer Qualification Response. Qualification Resolution
        /// <para />Cardinality: 1..n
        /// <para />ObjectClass: Tenderer Qualification Response
        /// <para />PropertyTerm: Qualification Resolution
        /// <para />AssociatedObjectClass: Qualification Resolution
        /// <para />RepresentationTerm: Qualification Resolution
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<QualificationResolutionType> QualificationResolution
        {
            get
            {
                if (__QualificationResolution == null) { __QualificationResolution = new System.Collections.Generic.List<QualificationResolutionType>(); }
                return __QualificationResolution;
            }
            set
            {
                __QualificationResolution = value;
            }
        }

        /// <summary>
        /// Terms of appeal for this tendering process.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Tenderer Qualification Response. Appeal Terms
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Tenderer Qualification Response
        /// <para />PropertyTerm: Appeal Terms
        /// <para />AssociatedObjectClass: Appeal Terms
        /// <para />RepresentationTerm: Appeal Terms
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public AppealTermsType AppealTerms
        {
            get
            {
                if (__AppealTerms == null) { __AppealTerms = new AppealTermsType(); }
                return __AppealTerms;
            }
            set
            {
                __AppealTerms = value;
            }
        }

    }
}
