// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace UblSharp
{
    using UnqualifiedDataTypes;
    using CommonAggregateComponents;
    using CommonExtensionComponents;
    
    
    /// <summary>
    /// An Invoice document created by the Customer (rather than the Supplier) in a Self Billing relationship.
    /// <para />ComponentType: ABIE
    /// <para />DictionaryEntryName: Self Billed Invoice. Details
    /// <para />ObjectClass: Self Billed Invoice
    /// </summary>
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SelfBilledInvoice", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:SelfBilledInvoice-2")]
    [System.Xml.Serialization.XmlRootAttribute("SelfBilledInvoice", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:SelfBilledInvoice-2", IsNullable=false)]
    public partial class SelfBilledInvoiceType : BaseDocument, IBaseDocument
    {
        
        [System.Xml.Serialization.XmlArrayAttribute("UBLExtensions", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UBLExtension", IsNullable=false)]
        public UBLExtensionType[] @__UBLExtensions
        {
            get
            {
                return UBLExtensions?.ToArray();
            }
            set
            {
                UBLExtensions = value == null ? null : new System.Collections.Generic.List<UBLExtensionType>(value);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("UBLVersionID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=1)]
        public IdentifierType @__UBLVersionID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("CustomizationID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=2)]
        public IdentifierType @__CustomizationID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ProfileID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=3)]
        public IdentifierType @__ProfileID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ProfileExecutionID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=4)]
        public IdentifierType @__ProfileExecutionID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=5)]
        public IdentifierType @__ID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("CopyIndicator", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=6)]
        public IndicatorType @__CopyIndicator;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("UUID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=7)]
        public IdentifierType @__UUID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("IssueDate", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=8)]
        public DateType @__IssueDate;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("IssueTime", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=9)]
        public TimeType @__IssueTime;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("TaxPointDate", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=10)]
        public DateType @__TaxPointDate;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("InvoiceTypeCode", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=11)]
        public CodeType @__InvoiceTypeCode;
        
        [System.Xml.Serialization.XmlElementAttribute("Note", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=12)]
        public TextType[] @__Note
        {
            get
            {
                return Note?.ToArray();
            }
            set
            {
                Note = value == null ? null : new System.Collections.Generic.List<TextType>(value);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("DocumentCurrencyCode", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=13)]
        public CodeType @__DocumentCurrencyCode;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("TaxCurrencyCode", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=14)]
        public CodeType @__TaxCurrencyCode;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("PricingCurrencyCode", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=15)]
        public CodeType @__PricingCurrencyCode;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("PaymentCurrencyCode", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=16)]
        public CodeType @__PaymentCurrencyCode;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("PaymentAlternativeCurrencyCode", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=17)]
        public CodeType @__PaymentAlternativeCurrencyCode;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("AccountingCostCode", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=18)]
        public CodeType @__AccountingCostCode;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("AccountingCost", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=19)]
        public TextType @__AccountingCost;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("LineCountNumeric", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=20)]
        public NumericType @__LineCountNumeric;
        
        [System.Xml.Serialization.XmlElementAttribute("InvoicePeriod", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=21)]
        public PeriodType[] @__InvoicePeriod
        {
            get
            {
                return InvoicePeriod?.ToArray();
            }
            set
            {
                InvoicePeriod = value == null ? null : new System.Collections.Generic.List<PeriodType>(value);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("OrderReference", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=22)]
        public OrderReferenceType @__OrderReference;
        
        [System.Xml.Serialization.XmlElementAttribute("BillingReference", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=23)]
        public BillingReferenceType[] @__BillingReference
        {
            get
            {
                return BillingReference?.ToArray();
            }
            set
            {
                BillingReference = value == null ? null : new System.Collections.Generic.List<BillingReferenceType>(value);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ContractDocumentReference", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=24)]
        public DocumentReferenceType[] @__ContractDocumentReference
        {
            get
            {
                return ContractDocumentReference?.ToArray();
            }
            set
            {
                ContractDocumentReference = value == null ? null : new System.Collections.Generic.List<DocumentReferenceType>(value);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DespatchDocumentReference", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=25)]
        public DocumentReferenceType[] @__DespatchDocumentReference
        {
            get
            {
                return DespatchDocumentReference?.ToArray();
            }
            set
            {
                DespatchDocumentReference = value == null ? null : new System.Collections.Generic.List<DocumentReferenceType>(value);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ReceiptDocumentReference", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=26)]
        public DocumentReferenceType[] @__ReceiptDocumentReference
        {
            get
            {
                return ReceiptDocumentReference?.ToArray();
            }
            set
            {
                ReceiptDocumentReference = value == null ? null : new System.Collections.Generic.List<DocumentReferenceType>(value);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("StatementDocumentReference", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=27)]
        public DocumentReferenceType[] @__StatementDocumentReference
        {
            get
            {
                return StatementDocumentReference?.ToArray();
            }
            set
            {
                StatementDocumentReference = value == null ? null : new System.Collections.Generic.List<DocumentReferenceType>(value);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OriginatorDocumentReference", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=28)]
        public DocumentReferenceType[] @__OriginatorDocumentReference
        {
            get
            {
                return OriginatorDocumentReference?.ToArray();
            }
            set
            {
                OriginatorDocumentReference = value == null ? null : new System.Collections.Generic.List<DocumentReferenceType>(value);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AdditionalDocumentReference", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=29)]
        public DocumentReferenceType[] @__AdditionalDocumentReference
        {
            get
            {
                return AdditionalDocumentReference?.ToArray();
            }
            set
            {
                AdditionalDocumentReference = value == null ? null : new System.Collections.Generic.List<DocumentReferenceType>(value);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=30)]
        public SignatureType[] @__Signature
        {
            get
            {
                return Signature?.ToArray();
            }
            set
            {
                Signature = value == null ? null : new System.Collections.Generic.List<SignatureType>(value);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("AccountingCustomerParty", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=31)]
        public CustomerPartyType @__AccountingCustomerParty;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("AccountingSupplierParty", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=32)]
        public SupplierPartyType @__AccountingSupplierParty;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("BuyerCustomerParty", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=33)]
        public CustomerPartyType @__BuyerCustomerParty;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("SellerSupplierParty", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=34)]
        public SupplierPartyType @__SellerSupplierParty;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("PayeeParty", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=35)]
        public PartyType @__PayeeParty;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("TaxRepresentativeParty", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=36)]
        public PartyType @__TaxRepresentativeParty;
        
        [System.Xml.Serialization.XmlElementAttribute("Delivery", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=37)]
        public DeliveryType[] @__Delivery
        {
            get
            {
                return Delivery?.ToArray();
            }
            set
            {
                Delivery = value == null ? null : new System.Collections.Generic.List<DeliveryType>(value);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DeliveryTerms", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=38)]
        public DeliveryTermsType[] @__DeliveryTerms
        {
            get
            {
                return DeliveryTerms?.ToArray();
            }
            set
            {
                DeliveryTerms = value == null ? null : new System.Collections.Generic.List<DeliveryTermsType>(value);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("PaymentMeans", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=39)]
        public PaymentMeansType @__PaymentMeans;
        
        [System.Xml.Serialization.XmlElementAttribute("PaymentTerms", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=40)]
        public PaymentTermsType[] @__PaymentTerms
        {
            get
            {
                return PaymentTerms?.ToArray();
            }
            set
            {
                PaymentTerms = value == null ? null : new System.Collections.Generic.List<PaymentTermsType>(value);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("PrepaidPayment", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=41)]
        public PaymentType[] @__PrepaidPayment
        {
            get
            {
                return PrepaidPayment?.ToArray();
            }
            set
            {
                PrepaidPayment = value == null ? null : new System.Collections.Generic.List<PaymentType>(value);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AllowanceCharge", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=42)]
        public AllowanceChargeType[] @__AllowanceCharge
        {
            get
            {
                return AllowanceCharge?.ToArray();
            }
            set
            {
                AllowanceCharge = value == null ? null : new System.Collections.Generic.List<AllowanceChargeType>(value);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("TaxExchangeRate", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=43)]
        public ExchangeRateType @__TaxExchangeRate;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("PricingExchangeRate", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=44)]
        public ExchangeRateType @__PricingExchangeRate;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("PaymentExchangeRate", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=45)]
        public ExchangeRateType @__PaymentExchangeRate;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("PaymentAlternativeExchangeRate", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=46)]
        public ExchangeRateType @__PaymentAlternativeExchangeRate;
        
        [System.Xml.Serialization.XmlElementAttribute("TaxTotal", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=47)]
        public TaxTotalType[] @__TaxTotal
        {
            get
            {
                return TaxTotal?.ToArray();
            }
            set
            {
                TaxTotal = value == null ? null : new System.Collections.Generic.List<TaxTotalType>(value);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("LegalMonetaryTotal", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=48)]
        public MonetaryTotalType @__LegalMonetaryTotal;
        
        [System.Xml.Serialization.XmlElementAttribute("InvoiceLine", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=49)]
        public InvoiceLineType[] @__InvoiceLine
        {
            get
            {
                return InvoiceLine?.ToArray();
            }
            set
            {
                InvoiceLine = value == null ? null : new System.Collections.Generic.List<InvoiceLineType>(value);
            }
        }
        
        /// <summary>
        /// A container for all extensions present in the document.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        System.Collections.Generic.List<UBLExtensionType> IBaseDocument.UBLExtensions { get; set; }

        
        /// <summary>
        /// Free-form text pertinent to this document, conveying information that is not contained explicitly in other structures.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Note. Text
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Note
        /// <para />RepresentationTerm: Text
        /// <para />DataType: Text. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<TextType> Note { get; set; }

        
        /// <summary>
        /// A period to which the Self Billed Invoice applies.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Invoice_ Period. Period
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Invoice
        /// <para />PropertyTerm: Period
        /// <para />AssociatedObjectClass: Period
        /// <para />RepresentationTerm: Period
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<PeriodType> InvoicePeriod { get; set; }

        
        /// <summary>
        /// A reference to a billing document associated with this document.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Billing Reference
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Billing Reference
        /// <para />AssociatedObjectClass: Billing Reference
        /// <para />RepresentationTerm: Billing Reference
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<BillingReferenceType> BillingReference { get; set; }

        
        /// <summary>
        /// A reference to a contract associated with this document.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Contract_ Document Reference. Document Reference
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Contract
        /// <para />PropertyTerm: Document Reference
        /// <para />AssociatedObjectClass: Document Reference
        /// <para />RepresentationTerm: Document Reference
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<DocumentReferenceType> ContractDocumentReference { get; set; }

        
        /// <summary>
        /// A reference to a Despatch Advice associated with this document.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Despatch_ Document Reference. Document Reference
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Despatch
        /// <para />PropertyTerm: Document Reference
        /// <para />AssociatedObjectClass: Document Reference
        /// <para />RepresentationTerm: Document Reference
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<DocumentReferenceType> DespatchDocumentReference { get; set; }

        
        /// <summary>
        /// A reference to a Receipt Advice associated with this document.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Receipt_ Document Reference. Document Reference
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Receipt
        /// <para />PropertyTerm: Document Reference
        /// <para />AssociatedObjectClass: Document Reference
        /// <para />RepresentationTerm: Document Reference
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<DocumentReferenceType> ReceiptDocumentReference { get; set; }

        
        /// <summary>
        /// A reference to a Statement associated with this document.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Statement_ Document Reference. Document Reference
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Statement
        /// <para />PropertyTerm: Document Reference
        /// <para />AssociatedObjectClass: Document Reference
        /// <para />RepresentationTerm: Document Reference
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<DocumentReferenceType> StatementDocumentReference { get; set; }

        
        /// <summary>
        /// A reference to an originator document associated with this document.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Originator_ Document Reference. Document Reference
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Originator
        /// <para />PropertyTerm: Document Reference
        /// <para />AssociatedObjectClass: Document Reference
        /// <para />RepresentationTerm: Document Reference
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<DocumentReferenceType> OriginatorDocumentReference { get; set; }

        
        /// <summary>
        /// A reference to an additional document associated with this document.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Additional_ Document Reference. Document Reference
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Additional
        /// <para />PropertyTerm: Document Reference
        /// <para />AssociatedObjectClass: Document Reference
        /// <para />RepresentationTerm: Document Reference
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<DocumentReferenceType> AdditionalDocumentReference { get; set; }

        
        /// <summary>
        /// A signature applied to this document.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Signature
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Signature
        /// <para />AssociatedObjectClass: Signature
        /// <para />RepresentationTerm: Signature
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        System.Collections.Generic.List<SignatureType> IBaseDocument.Signature { get; set; }

        
        /// <summary>
        /// A delivery associated with this document.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Delivery
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Delivery
        /// <para />AssociatedObjectClass: Delivery
        /// <para />RepresentationTerm: Delivery
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<DeliveryType> Delivery { get; set; }

        
        /// <summary>
        /// A set of delivery terms associated with this document.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Delivery Terms
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Delivery Terms
        /// <para />AssociatedObjectClass: Delivery Terms
        /// <para />RepresentationTerm: Delivery Terms
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<DeliveryTermsType> DeliveryTerms { get; set; }

        
        /// <summary>
        /// A set of payment terms associated with this document.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Payment Terms
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Payment Terms
        /// <para />AssociatedObjectClass: Payment Terms
        /// <para />RepresentationTerm: Payment Terms
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<PaymentTermsType> PaymentTerms { get; set; }

        
        /// <summary>
        /// A prepaid payment.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Prepaid_ Payment. Payment
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Prepaid
        /// <para />PropertyTerm: Payment
        /// <para />AssociatedObjectClass: Payment
        /// <para />RepresentationTerm: Payment
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<PaymentType> PrepaidPayment { get; set; }

        
        /// <summary>
        /// A discount or charge that applies to a price component.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Allowance Charge
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Allowance Charge
        /// <para />AssociatedObjectClass: Allowance Charge
        /// <para />RepresentationTerm: Allowance Charge
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<AllowanceChargeType> AllowanceCharge { get; set; }

        
        /// <summary>
        /// The total amount of a specific type of tax.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Tax Total
        /// <para />Cardinality: 0..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Tax Total
        /// <para />AssociatedObjectClass: Tax Total
        /// <para />RepresentationTerm: Tax Total
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<TaxTotalType> TaxTotal { get; set; }

        
        /// <summary>
        /// A line describing an Invoice Item.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Invoice Line
        /// <para />Cardinality: 1..n
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Invoice Line
        /// <para />AssociatedObjectClass: Invoice Line
        /// <para />RepresentationTerm: Invoice Line
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<InvoiceLineType> InvoiceLine { get; set; }

        
        /// <summary>
        /// Identifies the earliest version of the UBL 2 schema for this document type that defines all of the elements that might be encountered in the current instance.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. UBL Version Identifier. Identifier
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: UBL Version Identifier
        /// <para />RepresentationTerm: Identifier
        /// <para />DataType: Identifier. Type
        /// </summary>
        /// <example>2.0.5</example>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        IdentifierType IBaseDocument.UBLVersionID
        {
            get
            {
                if (__UBLVersionID == null) { __UBLVersionID = new IdentifierType(); }
                return __UBLVersionID;
            }
            set
            {
                __UBLVersionID = value;
            }
        }

        
        /// <summary>
        /// Identifies a user-defined customization of UBL for a specific use.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Customization Identifier. Identifier
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Customization Identifier
        /// <para />RepresentationTerm: Identifier
        /// <para />DataType: Identifier. Type
        /// </summary>
        /// <example>NES</example>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        IdentifierType IBaseDocument.CustomizationID
        {
            get
            {
                if (__CustomizationID == null) { __CustomizationID = new IdentifierType(); }
                return __CustomizationID;
            }
            set
            {
                __CustomizationID = value;
            }
        }

        
        /// <summary>
        /// Identifies a user-defined profile of the customization of UBL being used.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Profile Identifier. Identifier
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Profile Identifier
        /// <para />RepresentationTerm: Identifier
        /// <para />DataType: Identifier. Type
        /// </summary>
        /// <example>BasicProcurementProcess</example>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        IdentifierType IBaseDocument.ProfileID
        {
            get
            {
                if (__ProfileID == null) { __ProfileID = new IdentifierType(); }
                return __ProfileID;
            }
            set
            {
                __ProfileID = value;
            }
        }

        
        /// <summary>
        /// Identifies an instance of executing a profile, to associate all transactions in a collaboration.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Profile Execution Identifier. Identifier
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Profile Execution Identifier
        /// <para />RepresentationTerm: Identifier
        /// <para />DataType: Identifier. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        IdentifierType IBaseDocument.ProfileExecutionID
        {
            get
            {
                if (__ProfileExecutionID == null) { __ProfileExecutionID = new IdentifierType(); }
                return __ProfileExecutionID;
            }
            set
            {
                __ProfileExecutionID = value;
            }
        }

        
        /// <summary>
        /// An identifier for this document, assigned by the sender.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Identifier
        /// <para />Cardinality: 1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Identifier
        /// <para />RepresentationTerm: Identifier
        /// <para />DataType: Identifier. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        IdentifierType IBaseDocument.ID
        {
            get
            {
                if (__ID == null) { __ID = new IdentifierType(); }
                return __ID;
            }
            set
            {
                __ID = value;
            }
        }

        
        /// <summary>
        /// Indicates whether this document is a copy (true) or not (false).
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Copy_ Indicator. Indicator
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Copy
        /// <para />PropertyTerm: Indicator
        /// <para />RepresentationTerm: Indicator
        /// <para />DataType: Indicator. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public IndicatorType CopyIndicator
        {
            get
            {
                if (__CopyIndicator == null) { __CopyIndicator = new IndicatorType(); }
                return __CopyIndicator;
            }
            set
            {
                __CopyIndicator = value;
            }
        }

        
        /// <summary>
        /// A universally unique identifier for an instance of this document.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. UUID. Identifier
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: UUID
        /// <para />RepresentationTerm: Identifier
        /// <para />DataType: Identifier. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        IdentifierType IBaseDocument.UUID
        {
            get
            {
                if (__UUID == null) { __UUID = new IdentifierType(); }
                return __UUID;
            }
            set
            {
                __UUID = value;
            }
        }

        
        /// <summary>
        /// The date, assigned by the sender, on which this document was issued.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Issue Date. Date
        /// <para />Cardinality: 1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Issue Date
        /// <para />RepresentationTerm: Date
        /// <para />DataType: Date. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public DateType IssueDate
        {
            get
            {
                if (__IssueDate == null) { __IssueDate = new DateType(); }
                return __IssueDate;
            }
            set
            {
                __IssueDate = value;
            }
        }

        
        /// <summary>
        /// The time, assigned by the sender, at which this document was issued.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Issue Time. Time
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Issue Time
        /// <para />RepresentationTerm: Time
        /// <para />DataType: Time. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public TimeType IssueTime
        {
            get
            {
                if (__IssueTime == null) { __IssueTime = new TimeType(); }
                return __IssueTime;
            }
            set
            {
                __IssueTime = value;
            }
        }

        
        /// <summary>
        /// The date of the invoice for tax purposes, in accordance with the applicable tax regulation.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Tax Point Date. Date
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Tax Point Date
        /// <para />RepresentationTerm: Date
        /// <para />DataType: Date. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public DateType TaxPointDate
        {
            get
            {
                if (__TaxPointDate == null) { __TaxPointDate = new DateType(); }
                return __TaxPointDate;
            }
            set
            {
                __TaxPointDate = value;
            }
        }

        
        /// <summary>
        /// A code signifying the type of invoice.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Invoice Type Code. Code
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Invoice Type Code
        /// <para />RepresentationTerm: Code
        /// <para />DataType: Code. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public CodeType InvoiceTypeCode
        {
            get
            {
                if (__InvoiceTypeCode == null) { __InvoiceTypeCode = new CodeType(); }
                return __InvoiceTypeCode;
            }
            set
            {
                __InvoiceTypeCode = value;
            }
        }

        
        /// <summary>
        /// A code signifying the default currency for this document.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Document_ Currency Code. Code
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Document
        /// <para />PropertyTerm: Currency Code
        /// <para />RepresentationTerm: Code
        /// <para />DataTypeQualifier: Currency
        /// <para />DataType: Currency_ Code. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public CodeType DocumentCurrencyCode
        {
            get
            {
                if (__DocumentCurrencyCode == null) { __DocumentCurrencyCode = new CodeType(); }
                return __DocumentCurrencyCode;
            }
            set
            {
                __DocumentCurrencyCode = value;
            }
        }

        
        /// <summary>
        /// A code signifying the currency used for tax amounts in the Invoice.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Tax_ Currency Code. Code
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Tax
        /// <para />PropertyTerm: Currency Code
        /// <para />RepresentationTerm: Code
        /// <para />DataTypeQualifier: Currency
        /// <para />DataType: Currency_ Code. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public CodeType TaxCurrencyCode
        {
            get
            {
                if (__TaxCurrencyCode == null) { __TaxCurrencyCode = new CodeType(); }
                return __TaxCurrencyCode;
            }
            set
            {
                __TaxCurrencyCode = value;
            }
        }

        
        /// <summary>
        /// A code signifying the currency used for prices in the Invoice.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Pricing_ Currency Code. Code
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Pricing
        /// <para />PropertyTerm: Currency Code
        /// <para />RepresentationTerm: Code
        /// <para />DataTypeQualifier: Currency
        /// <para />DataType: Currency_ Code. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public CodeType PricingCurrencyCode
        {
            get
            {
                if (__PricingCurrencyCode == null) { __PricingCurrencyCode = new CodeType(); }
                return __PricingCurrencyCode;
            }
            set
            {
                __PricingCurrencyCode = value;
            }
        }

        
        /// <summary>
        /// A code signifying the currency used for payment in the Invoice.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Payment_ Currency Code. Code
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Payment
        /// <para />PropertyTerm: Currency Code
        /// <para />RepresentationTerm: Code
        /// <para />DataTypeQualifier: Currency
        /// <para />DataType: Currency_ Code. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public CodeType PaymentCurrencyCode
        {
            get
            {
                if (__PaymentCurrencyCode == null) { __PaymentCurrencyCode = new CodeType(); }
                return __PaymentCurrencyCode;
            }
            set
            {
                __PaymentCurrencyCode = value;
            }
        }

        
        /// <summary>
        /// A code signifying the alternative currency used for payment in the Invoice.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Payment Alternative_ Currency Code. Code
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Payment Alternative
        /// <para />PropertyTerm: Currency Code
        /// <para />RepresentationTerm: Code
        /// <para />DataTypeQualifier: Currency
        /// <para />DataType: Currency_ Code. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public CodeType PaymentAlternativeCurrencyCode
        {
            get
            {
                if (__PaymentAlternativeCurrencyCode == null) { __PaymentAlternativeCurrencyCode = new CodeType(); }
                return __PaymentAlternativeCurrencyCode;
            }
            set
            {
                __PaymentAlternativeCurrencyCode = value;
            }
        }

        
        /// <summary>
        /// An accounting cost code, applied to the Invoice as a whole.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Accounting Cost Code. Code
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Accounting Cost Code
        /// <para />RepresentationTerm: Code
        /// <para />DataType: Code. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public CodeType AccountingCostCode
        {
            get
            {
                if (__AccountingCostCode == null) { __AccountingCostCode = new CodeType(); }
                return __AccountingCostCode;
            }
            set
            {
                __AccountingCostCode = value;
            }
        }

        
        /// <summary>
        /// An accounting cost code, applied to the Invoice as a whole, expressed as text.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Accounting Cost. Text
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Accounting Cost
        /// <para />RepresentationTerm: Text
        /// <para />DataType: Text. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public TextType AccountingCost
        {
            get
            {
                if (__AccountingCost == null) { __AccountingCost = new TextType(); }
                return __AccountingCost;
            }
            set
            {
                __AccountingCost = value;
            }
        }

        
        /// <summary>
        /// The number of Invoice Lines in this document.
        /// <para />ComponentType: BBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Line Count. Numeric
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Line Count
        /// <para />RepresentationTerm: Numeric
        /// <para />DataType: Numeric. Type
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public NumericType LineCountNumeric
        {
            get
            {
                if (__LineCountNumeric == null) { __LineCountNumeric = new NumericType(); }
                return __LineCountNumeric;
            }
            set
            {
                __LineCountNumeric = value;
            }
        }

        
        /// <summary>
        /// A reference to the Order with which this Invoice is associated.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Order Reference
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Order Reference
        /// <para />AssociatedObjectClass: Order Reference
        /// <para />RepresentationTerm: Order Reference
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public OrderReferenceType OrderReference
        {
            get
            {
                if (__OrderReference == null) { __OrderReference = new OrderReferenceType(); }
                return __OrderReference;
            }
            set
            {
                __OrderReference = value;
            }
        }

        
        /// <summary>
        /// The accounting customer party.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Accounting_ Customer Party. Customer Party
        /// <para />Cardinality: 1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Accounting
        /// <para />PropertyTerm: Customer Party
        /// <para />AssociatedObjectClass: Customer Party
        /// <para />RepresentationTerm: Customer Party
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public CustomerPartyType AccountingCustomerParty
        {
            get
            {
                if (__AccountingCustomerParty == null) { __AccountingCustomerParty = new CustomerPartyType(); }
                return __AccountingCustomerParty;
            }
            set
            {
                __AccountingCustomerParty = value;
            }
        }

        
        /// <summary>
        /// The accounting supplier party.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Accounting_ Supplier Party. Supplier Party
        /// <para />Cardinality: 1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Accounting
        /// <para />PropertyTerm: Supplier Party
        /// <para />AssociatedObjectClass: Supplier Party
        /// <para />RepresentationTerm: Supplier Party
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public SupplierPartyType AccountingSupplierParty
        {
            get
            {
                if (__AccountingSupplierParty == null) { __AccountingSupplierParty = new SupplierPartyType(); }
                return __AccountingSupplierParty;
            }
            set
            {
                __AccountingSupplierParty = value;
            }
        }

        
        /// <summary>
        /// The buyer.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Buyer_ Customer Party. Customer Party
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Buyer
        /// <para />PropertyTerm: Customer Party
        /// <para />AssociatedObjectClass: Customer Party
        /// <para />RepresentationTerm: Customer Party
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public CustomerPartyType BuyerCustomerParty
        {
            get
            {
                if (__BuyerCustomerParty == null) { __BuyerCustomerParty = new CustomerPartyType(); }
                return __BuyerCustomerParty;
            }
            set
            {
                __BuyerCustomerParty = value;
            }
        }

        
        /// <summary>
        /// The seller.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Seller_ Supplier Party. Supplier Party
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Seller
        /// <para />PropertyTerm: Supplier Party
        /// <para />AssociatedObjectClass: Supplier Party
        /// <para />RepresentationTerm: Supplier Party
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public SupplierPartyType SellerSupplierParty
        {
            get
            {
                if (__SellerSupplierParty == null) { __SellerSupplierParty = new SupplierPartyType(); }
                return __SellerSupplierParty;
            }
            set
            {
                __SellerSupplierParty = value;
            }
        }

        
        /// <summary>
        /// The payee.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Payee_ Party. Party
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Payee
        /// <para />PropertyTerm: Party
        /// <para />AssociatedObjectClass: Party
        /// <para />RepresentationTerm: Party
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public PartyType PayeeParty
        {
            get
            {
                if (__PayeeParty == null) { __PayeeParty = new PartyType(); }
                return __PayeeParty;
            }
            set
            {
                __PayeeParty = value;
            }
        }

        
        /// <summary>
        /// The tax representative.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Tax Representative_ Party. Party
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Tax Representative
        /// <para />PropertyTerm: Party
        /// <para />AssociatedObjectClass: Party
        /// <para />RepresentationTerm: Party
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public PartyType TaxRepresentativeParty
        {
            get
            {
                if (__TaxRepresentativeParty == null) { __TaxRepresentativeParty = new PartyType(); }
                return __TaxRepresentativeParty;
            }
            set
            {
                __TaxRepresentativeParty = value;
            }
        }

        
        /// <summary>
        /// Expected means of payment.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Payment Means
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTerm: Payment Means
        /// <para />AssociatedObjectClass: Payment Means
        /// <para />RepresentationTerm: Payment Means
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public PaymentMeansType PaymentMeans
        {
            get
            {
                if (__PaymentMeans == null) { __PaymentMeans = new PaymentMeansType(); }
                return __PaymentMeans;
            }
            set
            {
                __PaymentMeans = value;
            }
        }

        
        /// <summary>
        /// The exchange rate between the document currency and the tax currency.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Tax_ Exchange Rate. Exchange Rate
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Tax
        /// <para />PropertyTerm: Exchange Rate
        /// <para />AssociatedObjectClass: Exchange Rate
        /// <para />RepresentationTerm: Exchange Rate
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ExchangeRateType TaxExchangeRate
        {
            get
            {
                if (__TaxExchangeRate == null) { __TaxExchangeRate = new ExchangeRateType(); }
                return __TaxExchangeRate;
            }
            set
            {
                __TaxExchangeRate = value;
            }
        }

        
        /// <summary>
        /// The exchange rate between the document currency and the pricing currency.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Pricing_ Exchange Rate. Exchange Rate
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Pricing
        /// <para />PropertyTerm: Exchange Rate
        /// <para />AssociatedObjectClass: Exchange Rate
        /// <para />RepresentationTerm: Exchange Rate
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ExchangeRateType PricingExchangeRate
        {
            get
            {
                if (__PricingExchangeRate == null) { __PricingExchangeRate = new ExchangeRateType(); }
                return __PricingExchangeRate;
            }
            set
            {
                __PricingExchangeRate = value;
            }
        }

        
        /// <summary>
        /// The exchange rate between the document currency and the payment currency.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Payment_ Exchange Rate. Exchange Rate
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Payment
        /// <para />PropertyTerm: Exchange Rate
        /// <para />AssociatedObjectClass: Exchange Rate
        /// <para />RepresentationTerm: Exchange Rate
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ExchangeRateType PaymentExchangeRate
        {
            get
            {
                if (__PaymentExchangeRate == null) { __PaymentExchangeRate = new ExchangeRateType(); }
                return __PaymentExchangeRate;
            }
            set
            {
                __PaymentExchangeRate = value;
            }
        }

        
        /// <summary>
        /// The exchange rate between the document currency and the payment alternative currency.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Payment Alternative_ Exchange Rate. Exchange Rate
        /// <para />Cardinality: 0..1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Payment Alternative
        /// <para />PropertyTerm: Exchange Rate
        /// <para />AssociatedObjectClass: Exchange Rate
        /// <para />RepresentationTerm: Exchange Rate
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ExchangeRateType PaymentAlternativeExchangeRate
        {
            get
            {
                if (__PaymentAlternativeExchangeRate == null) { __PaymentAlternativeExchangeRate = new ExchangeRateType(); }
                return __PaymentAlternativeExchangeRate;
            }
            set
            {
                __PaymentAlternativeExchangeRate = value;
            }
        }

        
        /// <summary>
        /// A set of totals associated with this Invoice that are required for the Invoice to be a legal document.
        /// <para />ComponentType: ASBIE
        /// <para />DictionaryEntryName: Self Billed Invoice. Legal_ Monetary Total. Monetary Total
        /// <para />Cardinality: 1
        /// <para />ObjectClass: Self Billed Invoice
        /// <para />PropertyTermQualifier: Legal
        /// <para />PropertyTerm: Monetary Total
        /// <para />AssociatedObjectClass: Monetary Total
        /// <para />RepresentationTerm: Monetary Total
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public MonetaryTotalType LegalMonetaryTotal
        {
            get
            {
                if (__LegalMonetaryTotal == null) { __LegalMonetaryTotal = new MonetaryTotalType(); }
                return __LegalMonetaryTotal;
            }
            set
            {
                __LegalMonetaryTotal = value;
            }
        }

    }
}
