// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace UblSharp.SignatureBasicComponents
{
    using UnqualifiedDataTypes;
    
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReferencedSignatureIDType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2")]
    public partial class ReferencedSignatureIDType : IdentifierType
    {
        
        public static implicit operator ReferencedSignatureIDType(string value)
        {
             return value == null ? null : new ReferencedSignatureIDType { Value = value };
        }

        public static implicit operator string(ReferencedSignatureIDType value)
        {
             return value.Value;
        }

    }
}
