// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace UblSharp.CommonExtensionComponents
{
    using UnqualifiedDataTypes;
    
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionReasonType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionReasonType : TextType
    {
        
        public static implicit operator ExtensionReasonType(string value)
        {
             return value == null ? null : new ExtensionReasonType { Value = value };
        }

        public static implicit operator string(ExtensionReasonType value)
        {
             return value.Value;
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionAgencyNameType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionAgencyNameType : TextType
    {
        
        public static implicit operator ExtensionAgencyNameType(string value)
        {
             return value == null ? null : new ExtensionAgencyNameType { Value = value };
        }

        public static implicit operator string(ExtensionAgencyNameType value)
        {
             return value.Value;
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionVersionIDType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionVersionIDType : IdentifierType
    {
        
        public static implicit operator ExtensionVersionIDType(string value)
        {
             return value == null ? null : new ExtensionVersionIDType { Value = value };
        }

        public static implicit operator string(ExtensionVersionIDType value)
        {
             return value.Value;
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionURIType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionURIType : IdentifierType
    {
        
        public static implicit operator ExtensionURIType(string value)
        {
             return value == null ? null : new ExtensionURIType { Value = value };
        }

        public static implicit operator string(ExtensionURIType value)
        {
             return value.Value;
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionAgencyURIType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionAgencyURIType : IdentifierType
    {
        
        public static implicit operator ExtensionAgencyURIType(string value)
        {
             return value == null ? null : new ExtensionAgencyURIType { Value = value };
        }

        public static implicit operator string(ExtensionAgencyURIType value)
        {
             return value.Value;
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionAgencyIDType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionAgencyIDType : IdentifierType
    {
        
        public static implicit operator ExtensionAgencyIDType(string value)
        {
             return value == null ? null : new ExtensionAgencyIDType { Value = value };
        }

        public static implicit operator string(ExtensionAgencyIDType value)
        {
             return value.Value;
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionReasonCodeType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionReasonCodeType : CodeType
    {
        
        public static implicit operator ExtensionReasonCodeType(string value)
        {
             return value == null ? null : new ExtensionReasonCodeType { Value = value };
        }

        public static implicit operator string(ExtensionReasonCodeType value)
        {
             return value.Value;
        }

    }
    
    /// <summary>
    /// A single extension for private use.
    /// </summary>
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UBLExtensionType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class UBLExtensionType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IdentifierType @__ID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Name", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public NameType @__Name;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionAgencyID")]
        public ExtensionAgencyIDType @__ExtensionAgencyID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionAgencyName")]
        public ExtensionAgencyNameType @__ExtensionAgencyName;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionVersionID")]
        public ExtensionVersionIDType @__ExtensionVersionID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionAgencyURI")]
        public ExtensionAgencyURIType @__ExtensionAgencyURI;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionURI")]
        public ExtensionURIType @__ExtensionURI;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionReasonCode")]
        public ExtensionReasonCodeType @__ExtensionReasonCode;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionReason")]
        public ExtensionReasonType @__ExtensionReason;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionContent")]
#if FEATURE_XMLDOCUMENT
        public System.Xml.XmlElement @__ExtensionContent;
#elif !FEATURE_XMLDOCUMENT && FEATURE_LINQ
        public System.Xml.Linq.XElement @__ExtensionContent;
#else
        public object @__ExtensionContent;
#endif
        
        /// <summary>
        /// An identifier for the Extension assigned by the creator of the extension.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public IdentifierType ID
        {
            get
            {
                if (__ID == null) { __ID = new IdentifierType(); }
                return __ID;
            }
            set
            {
                __ID = value;
            }
        }

        /// <summary>
        /// A name for the Extension assigned by the creator of the extension.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public NameType Name
        {
            get
            {
                if (__Name == null) { __Name = new NameType(); }
                return __Name;
            }
            set
            {
                __Name = value;
            }
        }

        /// <summary>
        /// An agency that maintains one or more Extensions.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ExtensionAgencyIDType ExtensionAgencyID
        {
            get
            {
                if (__ExtensionAgencyID == null) { __ExtensionAgencyID = new ExtensionAgencyIDType(); }
                return __ExtensionAgencyID;
            }
            set
            {
                __ExtensionAgencyID = value;
            }
        }

        /// <summary>
        /// The name of the agency that maintains the Extension.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ExtensionAgencyNameType ExtensionAgencyName
        {
            get
            {
                if (__ExtensionAgencyName == null) { __ExtensionAgencyName = new ExtensionAgencyNameType(); }
                return __ExtensionAgencyName;
            }
            set
            {
                __ExtensionAgencyName = value;
            }
        }

        /// <summary>
        /// The version of the Extension.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ExtensionVersionIDType ExtensionVersionID
        {
            get
            {
                if (__ExtensionVersionID == null) { __ExtensionVersionID = new ExtensionVersionIDType(); }
                return __ExtensionVersionID;
            }
            set
            {
                __ExtensionVersionID = value;
            }
        }

        /// <summary>
        /// A URI for the Agency that maintains the Extension.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ExtensionAgencyURIType ExtensionAgencyURI
        {
            get
            {
                if (__ExtensionAgencyURI == null) { __ExtensionAgencyURI = new ExtensionAgencyURIType(); }
                return __ExtensionAgencyURI;
            }
            set
            {
                __ExtensionAgencyURI = value;
            }
        }

        /// <summary>
        /// A URI for the Extension.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ExtensionURIType ExtensionURI
        {
            get
            {
                if (__ExtensionURI == null) { __ExtensionURI = new ExtensionURIType(); }
                return __ExtensionURI;
            }
            set
            {
                __ExtensionURI = value;
            }
        }

        /// <summary>
        /// A code for reason the Extension is being included.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ExtensionReasonCodeType ExtensionReasonCode
        {
            get
            {
                if (__ExtensionReasonCode == null) { __ExtensionReasonCode = new ExtensionReasonCodeType(); }
                return __ExtensionReasonCode;
            }
            set
            {
                __ExtensionReasonCode = value;
            }
        }

        /// <summary>
        /// A description of the reason for the Extension.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ExtensionReasonType ExtensionReason
        {
            get
            {
                if (__ExtensionReason == null) { __ExtensionReason = new ExtensionReasonType(); }
                return __ExtensionReason;
            }
            set
            {
                __ExtensionReason = value;
            }
        }

        /// <summary>
        /// The definition of the extension content.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute]
#if FEATURE_XMLDOCUMENT
        public System.Xml.XmlElement ExtensionContent
#elif !FEATURE_XMLDOCUMENT && FEATURE_LINQ
        public System.Xml.Linq.XElement ExtensionContent
#else
        public object ExtensionContent
#endif
        {
            get
            {
                return __ExtensionContent;
            }
            set
            {
                __ExtensionContent = value;
            }
        }

    }
}
