// Generated by UblSharp.Tests.Generator
using System;
using System.Collections.Generic;
using System.Xml;
using UblSharp;
using UblSharp.CommonAggregateComponents;
using UblSharp.CommonExtensionComponents;
using UblSharp.UnqualifiedDataTypes;
using UblSharp.XmlDigitalSignature;
using UblSharp.Tests.Util;

namespace UblSharp.Tests.Samples
{
    internal class UBLTransportationStatus21Example
    {
        public static TransportationStatusType Create()
        {
            var doc = new TransportationStatusType
            {
                UBLVersionID = "2.1",
                ID = "TS_1",
                IssueDate = "2011-10-06",
                IssueTime = "09:29:30+01:00",
                TransportationStatusTypeCode = "All deviations",
                TransportExecutionStatusCode = "35",
                Consignment = new List<ConsignmentType>()
                {
                    new ConsignmentType
                    {
                        ID = "CON_1",
                        TransportHandlingUnit = new List<TransportHandlingUnitType>()
                        {
                            new TransportHandlingUnitType
                            {
                                ID = "CON_THU_1",
                                TransportEquipment = new List<TransportEquipmentType>()
                                {
                                    new TransportEquipmentType
                                    {
                                        ID = "CON_TE_1"
                                    }
                                },
                                Status = new List<StatusType>()
                                {
                                    new StatusType
                                    {
                                        ConditionCode = "4",
                                        StatusReasonCode = "23",
                                        StatusReason = new List<TextType>()
                                        {
                                            new TextType
                                            {
                                                Value = "Reefer container lost power - cargo of fish destroyed"
                                            }
                                        },
                                    }
                                },
                            }
                        },
                    }
                },
                TransportExecutionPlanDocumentReference = new DocumentReferenceType
                {
                    ID = "TEP_1"
                }
            };
            doc.Xmlns = new System.Xml.Serialization.XmlSerializerNamespaces(new[]
            {
                new XmlQualifiedName("cac","urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"),
                new XmlQualifiedName("cbc","urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"),
            });
            return doc;
        }
    }
}
