// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace UblSharp.SCSN
{
    using UblSharp;
    using UblSharp.CommonAggregateComponents;
    using UblSharp.UnqualifiedDataTypes;
    using UblSharp.CommonExtensionComponents;
    
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BillOfMaterials", Namespace = "SmartConnectedSupplierNetwork:schema:xsd:BillOfMaterials")]
    [System.Xml.Serialization.XmlRootAttribute("BillOfMaterials", Namespace = "SmartConnectedSupplierNetwork:schema:xsd:BillOfMaterials", IsNullable=false)]
    public partial class BillOfMaterialsType : BaseDocument, IBaseDocument
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=0)]
        public IdentifierType @__ID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("VersionID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=1)]
        public IdentifierType @__VersionID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("IssueDate", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=2)]
        public DateType @__IssueDate;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("DocumentStatusCode", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=3)]
        public CodeType @__DocumentStatusCode;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("BuyerCustomerParty", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=4)]
        public CustomerPartyType @__BuyerCustomerParty;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("SellerSupplierParty", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=5)]
        public SupplierPartyType @__SellerSupplierParty;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("BuyersItemIdentification", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=6)]
        public ItemIdentificationType @__BuyersItemIdentification;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("SellersItemIdentification", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=7)]
        public ItemIdentificationType @__SellersItemIdentification;
        
        private System.Collections.Generic.List<BOMLineType> _bOMLine;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("BOMLine", Order=8)]
        public BOMLineType[] @__BOMLine
        {
            get
            {
                return _bOMLine?.ToArray();
            }
            set
            {
                _bOMLine = value == null ? null : new System.Collections.Generic.List<BOMLineType>(value);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<BOMLineType> BOMLine
        {
            get { return _bOMLine ?? (_bOMLine = new System.Collections.Generic.List<BOMLineType>()); }
            set { _bOMLine = value; }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        IdentifierType IBaseDocument.ID
        {
            get
            {
                if (__ID == null) { __ID = new IdentifierType(); }
                return __ID;
            }
            set
            {
                __ID = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public IdentifierType VersionID
        {
            get
            {
                if (__VersionID == null) { __VersionID = new IdentifierType(); }
                return __VersionID;
            }
            set
            {
                __VersionID = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public DateType IssueDate
        {
            get
            {
                if (__IssueDate == null) { __IssueDate = new DateType(); }
                return __IssueDate;
            }
            set
            {
                __IssueDate = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public CodeType DocumentStatusCode
        {
            get
            {
                if (__DocumentStatusCode == null) { __DocumentStatusCode = new CodeType(); }
                return __DocumentStatusCode;
            }
            set
            {
                __DocumentStatusCode = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public CustomerPartyType BuyerCustomerParty
        {
            get
            {
                if (__BuyerCustomerParty == null) { __BuyerCustomerParty = new CustomerPartyType(); }
                return __BuyerCustomerParty;
            }
            set
            {
                __BuyerCustomerParty = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public SupplierPartyType SellerSupplierParty
        {
            get
            {
                if (__SellerSupplierParty == null) { __SellerSupplierParty = new SupplierPartyType(); }
                return __SellerSupplierParty;
            }
            set
            {
                __SellerSupplierParty = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ItemIdentificationType BuyersItemIdentification
        {
            get
            {
                if (__BuyersItemIdentification == null) { __BuyersItemIdentification = new ItemIdentificationType(); }
                return __BuyersItemIdentification;
            }
            set
            {
                __BuyersItemIdentification = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ItemIdentificationType SellersItemIdentification
        {
            get
            {
                if (__SellersItemIdentification == null) { __SellersItemIdentification = new ItemIdentificationType(); }
                return __SellersItemIdentification;
            }
            set
            {
                __SellersItemIdentification = value;
            }
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReferenceDesignatorType", Namespace = "SmartConnectedSupplierNetwork:schema:xsd:BillOfMaterials")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "SmartConnectedSupplierNetwork:schema:xsd:BillOfMaterials", IsNullable=true)]
    public partial class ReferenceDesignatorType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("PositionID", Order=0)]
        public IdentifierType @__PositionID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Description", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=1)]
        public TextType @__Description;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Quantity", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=2)]
        public QuantityType @__Quantity;
        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public IdentifierType PositionID
        {
            get
            {
                if (__PositionID == null) { __PositionID = new IdentifierType(); }
                return __PositionID;
            }
            set
            {
                __PositionID = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public TextType Description
        {
            get
            {
                if (__Description == null) { __Description = new TextType(); }
                return __Description;
            }
            set
            {
                __Description = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public QuantityType Quantity
        {
            get
            {
                if (__Quantity == null) { __Quantity = new QuantityType(); }
                return __Quantity;
            }
            set
            {
                __Quantity = value;
            }
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BOMLineType", Namespace = "SmartConnectedSupplierNetwork:schema:xsd:BillOfMaterials")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "SmartConnectedSupplierNetwork:schema:xsd:BillOfMaterials", IsNullable=true)]
    public partial class BOMLineType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("LineID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=0)]
        public IdentifierType @__LineID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Quantity", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=1)]
        public QuantityType @__Quantity;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Item", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=2)]
        public ItemType @__Item;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ValidityPeriod", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order=3)]
        public PeriodType @__ValidityPeriod;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("SubstituteLineID", Order=4)]
        public IdentifierType @__SubstituteLineID;
        
        private System.Collections.Generic.List<ItemType> _alternativeItem;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("AlternativeItem", Order=5)]
        public ItemType[] @__AlternativeItem
        {
            get
            {
                return _alternativeItem?.ToArray();
            }
            set
            {
                _alternativeItem = value == null ? null : new System.Collections.Generic.List<ItemType>(value);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("TrackingIndicator", Order=6)]
        public bool @__TrackingIndicator;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("SerialIDRegistrationIndicator", Order=7)]
        public bool @__SerialIDRegistrationIndicator;
        
        private System.Collections.Generic.List<IdentifierType> _instructionCode;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("InstructionCode", Order=8)]
        public IdentifierType[] @__InstructionCode
        {
            get
            {
                return _instructionCode?.ToArray();
            }
            set
            {
                _instructionCode = value == null ? null : new System.Collections.Generic.List<IdentifierType>(value);
            }
        }
        
        private System.Collections.Generic.List<ReferenceDesignatorType> _referenceDesignator;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceDesignator", Order=9)]
        public ReferenceDesignatorType[] @__ReferenceDesignator
        {
            get
            {
                return _referenceDesignator?.ToArray();
            }
            set
            {
                _referenceDesignator = value == null ? null : new System.Collections.Generic.List<ReferenceDesignatorType>(value);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("MultipartIndicator", Order=10)]
        public bool @__MultipartIndicator;
        
        private System.Collections.Generic.List<System.Object> _items;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("BOMLine", typeof(BOMLineType), Order=11)]
        [System.Xml.Serialization.XmlElementAttribute("BOMReference", typeof(BOMLineTypeBOMReference), Order=11)]
        public object[] @__Items
        {
            get
            {
                return _items?.ToArray();
            }
            set
            {
                _items = value == null ? null : new System.Collections.Generic.List<System.Object>(value);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Note", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=12)]
        public TextType @__Note;
        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<ItemType> AlternativeItem
        {
            get { return _alternativeItem ?? (_alternativeItem = new System.Collections.Generic.List<ItemType>()); }
            set { _alternativeItem = value; }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<IdentifierType> InstructionCode
        {
            get { return _instructionCode ?? (_instructionCode = new System.Collections.Generic.List<IdentifierType>()); }
            set { _instructionCode = value; }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<ReferenceDesignatorType> ReferenceDesignator
        {
            get { return _referenceDesignator ?? (_referenceDesignator = new System.Collections.Generic.List<ReferenceDesignatorType>()); }
            set { _referenceDesignator = value; }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<System.Object> Items
        {
            get { return _items ?? (_items = new System.Collections.Generic.List<System.Object>()); }
            set { _items = value; }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public IdentifierType LineID
        {
            get
            {
                if (__LineID == null) { __LineID = new IdentifierType(); }
                return __LineID;
            }
            set
            {
                __LineID = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public QuantityType Quantity
        {
            get
            {
                if (__Quantity == null) { __Quantity = new QuantityType(); }
                return __Quantity;
            }
            set
            {
                __Quantity = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ItemType Item
        {
            get
            {
                if (__Item == null) { __Item = new ItemType(); }
                return __Item;
            }
            set
            {
                __Item = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public PeriodType ValidityPeriod
        {
            get
            {
                if (__ValidityPeriod == null) { __ValidityPeriod = new PeriodType(); }
                return __ValidityPeriod;
            }
            set
            {
                __ValidityPeriod = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public IdentifierType SubstituteLineID
        {
            get
            {
                if (__SubstituteLineID == null) { __SubstituteLineID = new IdentifierType(); }
                return __SubstituteLineID;
            }
            set
            {
                __SubstituteLineID = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool TrackingIndicator
        {
            get
            {
                return __TrackingIndicator;
            }
            set
            {
                __TrackingIndicator = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool SerialIDRegistrationIndicator
        {
            get
            {
                return __SerialIDRegistrationIndicator;
            }
            set
            {
                __SerialIDRegistrationIndicator = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool MultipartIndicator
        {
            get
            {
                return __MultipartIndicator;
            }
            set
            {
                __MultipartIndicator = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public TextType Note
        {
            get
            {
                if (__Note == null) { __Note = new TextType(); }
                return __Note;
            }
            set
            {
                __Note = value;
            }
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BOMLineTypeBOMReference", AnonymousType=true, Namespace = "SmartConnectedSupplierNetwork:schema:xsd:BillOfMaterials")]
    public partial class BOMLineTypeBOMReference : DocumentReferenceType
    {
    }
}
